server:
  port: 7080

spring:
  redis:
    database: 2
    host: localhost
    port: 6379
    password: cloud123.mapgis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 691216
    url: jdbc:mysql://127.0.0.1/cristina?useSSL=false&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall

mybatis:
  mapper-locations: classpath*:com/jiangwei/authserver/mapper/*.xml
  typeAliasesPackage: com.jiangwei.authserver.entity